# Generated by Django 3.2.3 on 2021-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('weight_file_name', models.CharField(max_length=50)),
                ('max_text_length', models.IntegerField()),
                ('max_summary_length', models.IntegerField()),
                ('x_tokenizer_name', models.CharField(max_length=50)),
                ('y_tokenizer_name', models.CharField(max_length=50)),
            ],
        ),
    ]
