# Generated by Django 3.2.3 on 2021-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictResult',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('user_input', models.TextField()),
                ('teacher_input', models.TextField()),
                ('user_input_abstract', models.TextField()),
                ('teacher_input_abstract', models.TextField()),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
