# Generated by Django 3.2.3 on 2021-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_auto_20210523_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictresult',
            name='similarity_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='predictresult',
            name='teacher_input_abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='predictresult',
            name='user_input_abstract',
            field=models.TextField(null=True),
        ),
    ]
