# Generated by Django 3.2.3 on 2021-05-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_auto_20210523_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predictresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predictresult',
            name='similarity_score',
            field=models.FloatField(default=0),
        ),
    ]
